### ISSUE TITLE
Mocha and Jasmine

### ISSUE THREAD

**Issue by joshpitzalis** [dwyl/learn-qunit#6]
I don't know what Mocha and Jasmine. The write assumes I do, just makes it a little more overwhelming. It sounds like it's not essential to what I am supposed to be learning. Can we just leave the references  out?

**Comment by nelsonic** [comment]
Good question. the reason those are in the note is in case anyone asks the question: "aren't some of these benefits the same as testing framework xyz...?"
its a pre-emptive answer. and agree 100% it would be clearer if it was formatted as a FAQ. want to submit a pull request with the change?
